# Generated by Django 4.1.5 on 2023-01-31 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="items",
            field=models.ManyToManyField(
                blank=True, related_name="order", to="customer.menuitem"
            ),
        ),
        migrations.AlterField(
            model_name="ordermodel",
            name="price",
            field=models.DecimalField(decimal_places=2, max_digits=7),
        ),
    ]
