# Generated by Django 4.1.5 on 2023-02-13 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0001_initial"),
    ]

    operations = []
