# Generated by Django 4.1.5 on 2023-02-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_auto_20230205_2020"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="availability",
            field=models.BooleanField(default=True),
        ),
    ]
