# Generated by Django 4.1.5 on 2023-02-13 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_auto_20230213_1531"),
    ]

    operations = []
