# Generated by Django 4.1.5 on 2023-02-23 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0002_rename_items_ordermodel_order_items"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
