# Generated by Django 4.1.5 on 2023-02-08 09:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_ordermodel_availability"),
    ]

    operations = [
        migrations.RenameField(
            model_name="menuitem",
            old_name="decription",
            new_name="description",
        ),
    ]
