# Generated by Django 4.1.5 on 2023-01-31 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_ordermodel_city_ordermodel_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="name",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
