# Generated by Django 4.1.5 on 2023-02-08 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_rename_decription_menuitem_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="availability",
        ),
        migrations.AddField(
            model_name="menuitem",
            name="availability",
            field=models.BooleanField(default=True),
        ),
    ]
