# Generated by Django 4.1.5 on 2023-05-18 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_ad"),
    ]

    operations = [
        migrations.AddField(
            model_name="ad",
            name="created_at",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
