# Generated by Django 4.1.5 on 2023-01-31 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0004_ordermodel_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="phone_number",
            field=models.CharField(max_length=15),
        ),
    ]
