# Generated by Django 4.1.5 on 2023-02-08 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0005_remove_ordermodel_availability_menuitem_availability"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="phone_number",
            field=models.CharField(default="N/A", max_length=20),
        ),
    ]
