# Generated by Django 4.1.5 on 2023-01-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_alter_ordermodel_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="is_paid",
            field=models.BooleanField(default=False),
        ),
    ]
