# Generated by Django 4.1.5 on 2023-02-08 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0006_alter_ordermodel_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordermodel",
            name="phone_number",
            field=models.CharField(max_length=15, null=True),
        ),
    ]
