# Generated by Django 4.1.5 on 2023-02-01 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0007_ordermodel_is_paid"),
    ]

    operations = [
        migrations.AddField(
            model_name="ordermodel",
            name="is_shipped",
            field=models.BooleanField(default=False),
        ),
    ]
