# Generated by Django 4.1.5 on 2023-02-13 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0003_auto_20230213_1536"),
        ("customer", "0007_alter_ordermodel_phone_number"),
    ]

    operations = []
