# Generated by Django 4.1.5 on 2023-05-26 10:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_ad_likes"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("created_on", models.DateTimeField(default=django.utils.timezone.now)),
                ("location", models.CharField(max_length=255)),
                ("sponsored", models.BooleanField(default=False)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="event_images/"),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("agriculture", "Agriculture"),
                    ("hardware", "Hardware"),
                    ("food", "Food"),
                    ("job", "jobs"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
