# Generated by Django 4.1.5 on 2023-02-14 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0010_menuitem_quantity"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="menuitem",
            name="quantity",
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
