# Generated by Django 4.1.5 on 2023-05-29 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0011_event_alter_ad_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="delivery_time",
            field=models.DurationField(
                blank=True,
                choices=[
                    (40, "40 minutes"),
                    (60, "1 hour"),
                    (90, "1 hour 30 minutes"),
                    (1440, "1 day"),
                    (2880, "2 days"),
                    (4320, "3 days"),
                    (10080, "1 week"),
                    (20160, "2 weeks"),
                    (43200, "1 month"),
                    (86400, "2 months"),
                ],
                null=True,
            ),
        ),
    ]
