# Generated by Django 4.1.5 on 2023-05-29 05:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0012_menuitem_delivery_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="menuitem",
            name="delivery_time",
            field=models.DurationField(
                blank=True,
                choices=[
                    (datetime.timedelta(seconds=2400), "40 minutes"),
                    (datetime.timedelta(seconds=3600), "1 hour"),
                    (datetime.timedelta(seconds=5400), "1 hour 30 minutes"),
                    (datetime.timedelta(days=1), "1 day"),
                    (datetime.timedelta(days=2), "2 days"),
                    (datetime.timedelta(days=3), "3 days"),
                    (datetime.timedelta(days=7), "1 week"),
                    (datetime.timedelta(days=14), "2 weeks"),
                    (datetime.timedelta(days=30), "1 month"),
                    (datetime.timedelta(days=60), "2 months"),
                ],
                null=True,
            ),
        ),
    ]
