# Generated by Django 4.1.5 on 2023-02-15 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0013_remove_orderitem_price_remove_ordermodel_quantity_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordermodel",
            name="price",
        ),
        migrations.AddField(
            model_name="ordermodel",
            name="order_items",
            field=models.ManyToManyField(to="customer.orderitem"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="customer.ordermodel"
            ),
        ),
    ]
