# Generated by Django 4.1.5 on 2023-06-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customer", "0016_alter_ad_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ad",
            name="category",
            field=models.CharField(
                blank=True,
                choices=[
                    ("item", "Items"),
                    ("agriculture", "Agriculture"),
                    ("hardware", "Hardware"),
                    ("food", "Food"),
                    ("job", "Jobs"),
                    ("electronics", "Electronics"),
                    ("fashion", "Fashion"),
                    ("home", "Home"),
                    ("books", "Books"),
                    ("health", "Health"),
                    ("beauty", "Beauty"),
                    ("sports", "Sports"),
                    ("toys", "Toys"),
                    ("automotive", "Automotive"),
                    ("music", "Music"),
                    ("art", "Art"),
                    ("collectibles", "Collectibles"),
                    ("baby", "Baby"),
                    ("pet", "Pet"),
                    ("tools", "Tools"),
                    ("outdoors", "Outdoors"),
                    ("jewelry", "Jewelry"),
                    ("movies", "Movies"),
                    ("games", "Games"),
                    ("crafts", "Crafts"),
                    ("office", "Office"),
                    ("travel", "Travel"),
                    ("fitness", "Fitness"),
                    ("antiques", "Antiques"),
                    ("instruments", "Instruments"),
                    ("party", "Party"),
                    ("vintage", "Vintage"),
                    ("technology", "Technology"),
                    ("furniture", "Furniture"),
                    ("kitchen", "Kitchen"),
                    ("cosmetics", "Cosmetics"),
                    ("stationery", "Stationery"),
                    ("gifts", "Gifts"),
                    ("medical", "Medical"),
                    ("real_estate", "Real Estate"),
                    ("services", "Services"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
