# Generated by Django 4.1.5 on 2023-01-21 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_post_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(default="default.jpg", upload_to="items"),
        ),
    ]
