# Generated by Django 4.1.5 on 2023-01-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0008_comment_delete_order"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="approved_comment",
        ),
    ]
