# Generated by Django 4.1.5 on 2023-01-27 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0010_post_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="author",
            new_name="user",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="created_date",
        ),
        migrations.RemoveField(
            model_name="comment",
            name="text",
        ),
        migrations.AddField(
            model_name="comment",
            name="content",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="comment",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.post"
            ),
        ),
    ]
