# Generated by Django 4.1.5 on 2023-01-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0011_rename_author_comment_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="whatsapp_number",
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
