# Generated by Django 4.1.5 on 2023-05-17 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0013_ad"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Ad",
        ),
    ]
